# Generated by Django 5.2.15 on 2026-06-28 16:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_full_name', unique=True),
        ),
    ]
