# Generated by Django 5.2.15 on 2026-06-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_joined_date_members_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
