# Generated by Django 5.2.15 on 2026-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='members',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
