# Generated by Django 5.2.15 on 2026-06-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_members_joined_date_members_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
