# Generated by Django 5.2.15 on 2026-06-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_members_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
